/*
This program has been developed by students from the bachelor Computer Science
at Utrecht University within the Software and Game project course.

©Copyright Utrecht University (Department of Information and Computing Sciences)
*/


package eu.iv4xr.ux.pxtesting;
import agents.EventsProducer;
import agents.LabRecruitsTestAgent;
import eu.iv4xr.ux.pxtesting.PlayerOneCharacterization;
import static eu.iv4xr.ux.pxtesting.PlayerOneCharacterization.*;
import eu.iv4xr.ux.pxtesting.TestSettings;
import agents.tactics.GoalLib;
import agents.tactics.TacticLib;
import environments.LabRecruitsConfig;
import environments.LabRecruitsEnvironment;
import eu.iv4xr.framework.extensions.occ.Emotion;
import eu.iv4xr.framework.extensions.occ.EmotionAppraisalSystem;
import eu.iv4xr.framework.extensions.occ.Event;
import eu.iv4xr.framework.extensions.occ.Emotion.EmotionType;
import eu.iv4xr.framework.extensions.occ.Event.Tick;
import eu.iv4xr.framework.mainConcepts.TestDataCollector;
import eu.iv4xr.framework.mainConcepts.WorldEntity;
import eu.iv4xr.framework.spatial.Vec3;
import helperclasses.datastructures.linq.QArrayList;
import logger.JsonLoggerInstrument;
import nl.uu.cs.aplib.mainConcepts.Environment;
import nl.uu.cs.aplib.mainConcepts.GoalStructure;
import nl.uu.cs.aplib.multiAgentSupport.Message;

import static org.junit.jupiter.api.Assertions.*;

import java.io.IOException;
import java.util.*;
import java.util.function.Function;

import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import game.Platform;
import game.LabRecruitsTestServer;
import world.BeliefState;
import static eu.iv4xr.ux.pxtesting.CSVExport.*;
import java.io.File;
import static eu.iv4xr.ux.pxtesting.TestSettings.*;
import static nl.uu.cs.aplib.AplibEDSL.*;
import java.nio.file.Paths;

/**
 * This class runs an OCC-based Player Experience (PX) evaluation on two
 * variations of the buttons_doors_1 level. (you have to specify which variant
 * to evaluate). This is a small level, but the place is on fire. The player
 * goal is to escape the level by reaching an "exit room" (marked by a goal-flag).
 * The room is guarded by a closed door, so the player has to solve a small puzzle
 * to open this door, and surviving the fire as well.
 * 
 * This will run an iv4xr agent to automatically explore and solve the level. An
 * OCC appraisal system is hooked to that agent that will calculate the
 * emotional state of the agent as it progress through the play. The emotions
 * are recorded in some csv files generated by the evaluation. There is a Python
 * script to visualize the results.
 */

public class PX_Testing_Lab1 {

    private static LabRecruitsTestServer labRecruitsTestServer;
    private static String labRecruitesExeRootDir;
    
    @BeforeAll
    static void start() {
        // TestSettings.USE_SERVER_FOR_TEST = false ;
        // Uncomment this to make the game's graphic visible:
        TestSettings.USE_GRAPHICS = true; 
        //Changing the root directory
        //It needs to point at the iv4xrDemo directory for the game execution, instead of the current directory. 
        String labRecruitesExeRootParent = new File(System.getProperty("user.dir")).getParent();
        //String labRecruitesExeRootParent = new File(System.getProperty("user.dir")).getParentFile().getParent();
        labRecruitesExeRootDir= new File(labRecruitesExeRootParent,"iv4xrDemo").getAbsolutePath();
        labRecruitsTestServer = TestSettings.start_LabRecruitsTestServer(labRecruitesExeRootDir);
    }
    

    @AfterAll
    static void close() {
        if (labRecruitsTestServer != null)
            labRecruitsTestServer.close();
    }

    void instrument(Environment env) {
        env.registerInstrumenter(new JsonLoggerInstrument()).turnOnDebugInstrumentation();
    }
    GoalStructure open_and_check_doors(LabRecruitsTestAgent testAgent, String activatingButton, String... doors) {

        GoalStructure[] subgoals = new GoalStructure[1 + 2 * doors.length];
        subgoals[0] = GoalLib.entityInteracted(activatingButton);
        for (int k = 0; k < doors.length; k++) {
            int i = 2 * k + 1;
            String doorId = doors[k];
            subgoals[i] = GoalLib.entityStateRefreshed(doorId);
            subgoals[i + 1] = GoalLib.entityInvariantChecked(testAgent, doorId, "" + doorId + " should be open",
                    (WorldEntity e) -> e.getBooleanProperty("isOpen"));
        }
        return SEQ(subgoals);
    }
    /**
     * Run a Player Experience evaluation on the selected variant of the
     * Lab1
     */
    @Test
    public void runPXEvaluation() throws InterruptedException, IOException {
        // choose your setup here:
        // closetReachableTest("buttons_doors_1_setup1") ;
        runPXEvaluation("lab1");

    }

    /**
     * Run a Player Experience evaluation on specified variant of the
     * buttons_doors_1 level. Emotion data are dumped in csv files.
     */
    public void runPXEvaluation(String button_doors1_setup) throws InterruptedException, IOException {


    	var config = new LabRecruitsConfig(button_doors1_setup, Paths.get(labRecruitesExeRootDir, "src", "test", "resources", "levels").toAbsolutePath().toString());
    	config.light_intensity = 0.3f;
        var environment = new LabRecruitsEnvironment(config);
        if (USE_INSTRUMENT)
            instrument(environment);

        try {
            if (TestSettings.USE_GRAPHICS) {
                System.out.println("You can drag then game window elsewhere for beter viewing. Then hit RETURN to continue.");
                new Scanner(System.in).nextLine();
            }

            // create a test agent
            var testAgent = new LabRecruitsTestAgent("agent0") // matches the ID in the CSV file
                    .attachState(new BeliefState()).attachEnvironment(environment);
            
            // we will use the following fiunctional testing task to steer the agent
            // to solve the level. The final goal is to get the agent into a goal-room.
            // This this room as an escape room. 
            var testingTask = SEQ(open_and_check_doors(testAgent, "b_hall_1", "d_store_e"),
                    open_and_check_doors(testAgent, "b_store", "d_store_n", "d_sidehall"),
                    GoalLib.entityInteracted("b_secret_1"),
                    open_and_check_doors(testAgent, "b_side", "d_sidehall", "d_lab_w", "d_bcroom"),
                    open_and_check_doors(testAgent, "b_secret_2", "d_closet"),
                    open_and_check_doors(testAgent, "b_closet", "d_theater_s", "d_theater_e"),
                    open_and_check_doors(testAgent, "b_lab_e", "d_tofinish"),
                    open_and_check_doors(testAgent, "b_finish", "d_finish"), GoalLib.positionsVisited(new Vec3(1,0,17)));
            
            // attaching the goal and testdata-collector
            var dataCollector = new TestDataCollector();
            testAgent.setTestDataCollector(dataCollector).setGoal(testingTask);

            // add an event-producer to the test agent so that it produce events for
            // emotion appraisals:
            EventsProducer eventsProducer = new EventsProducer().attachTestAgent(testAgent);

            // Create an emotion appraiser, and hook it to the agent:
            EmotionAppraisalSystem eas = new EmotionAppraisalSystem(testAgent.getId());
            eas.attachEmotionBeliefBase(new EmotionBeliefBase().attachFunctionalState(testAgent.getState()))
                    .withUserModel(new PlayerOneCharacterization()).addGoal(questIsCompleted, 50)
                    .addGoal(gotAsMuchPointsAsPossible, 50).addInitialEmotions();

            // some lists for collecting experiment data:
            List<String[]> csvData_goalQuestIsCompleted = new LinkedList<>();
            String[] csvRow = { "t", "x", "y", "hope", "joy", "satisfaction", "fear" };
            csvData_goalQuestIsCompleted.add(csvRow);
            List<String[]> csvData_goalGetMuchPoints = new LinkedList<>();
            csvData_goalGetMuchPoints.add(csvRow);
            Function<Emotion, Float> normalizeIntensity = e -> e != null ? (float) e.intensity / 800f : 0f;

            environment.startSimulation(); // this will press the "Play" button in the game for you
            // goal not achieved yet
            assertFalse(testAgent.success());

            int i = 0;
            // ok, let's now run the agent:
            while (testingTask.getStatus().inProgress()) {
                Vec3 position = testAgent.getState().worldmodel.position;
                System.out.println("*** " + i + ", " + testAgent.getState().id + " @" + position);
                eventsProducer.generateCurrentEvents();
                if (eventsProducer.currentEvents.isEmpty()) {
                    eas.update(new Tick(), i);
                }
                else {
                    for (Message m : eventsProducer.currentEvents) {
                        eas.update( new LREvent(m.getMsgName()), i);
                    }
                }
                
                if (position != null) {
                    Vec3 p_ = position.copy();
                    p_.z = 8 - p_.z;
                    Float score = (float) testAgent.getState().worldmodel.score;
                    System.out.println("*** score=" + score);

                    float hope_completingQuest = normalizeIntensity
                            .apply(eas.getEmotion(questIsCompleted.name, EmotionType.Hope));
                    float joy_completingQuest = normalizeIntensity
                            .apply(eas.getEmotion(questIsCompleted.name, EmotionType.Joy));
                    float satisfaction_completingQuest = normalizeIntensity
                            .apply(eas.getEmotion(questIsCompleted.name, EmotionType.Satisfaction));
                    float fear_completingQuest = normalizeIntensity
                            .apply(eas.getEmotion(questIsCompleted.name, EmotionType.Fear));

                    float hope_getMuchPoints = normalizeIntensity
                            .apply(eas.getEmotion(gotAsMuchPointsAsPossible.name, EmotionType.Hope));
                    float joy_getMuchPoints = normalizeIntensity
                            .apply(eas.getEmotion(gotAsMuchPointsAsPossible.name, EmotionType.Joy));
                    float satisfaction_getMuchPoints = normalizeIntensity
                            .apply(eas.getEmotion(gotAsMuchPointsAsPossible.name, EmotionType.Satisfaction));
                    float fear_getMuchPoints = normalizeIntensity
                            .apply(eas.getEmotion(gotAsMuchPointsAsPossible.name, EmotionType.Fear));

                    String[] csvRow1 = { "" + i, "" + p_.x, "" + p_.z, "" + hope_completingQuest,
                            "" + joy_completingQuest, "" + satisfaction_completingQuest, "" + fear_completingQuest };

                    String[] csvRow2 = { "" + i, "" + p_.x, "" + p_.z, "" + hope_getMuchPoints, "" + joy_getMuchPoints,
                            "" + satisfaction_getMuchPoints, "" + fear_getMuchPoints };

                    csvData_goalQuestIsCompleted.add(csvRow1);
                    csvData_goalGetMuchPoints.add(csvRow2);
                }
                Thread.sleep(50);
                i++;
                testAgent.update();
                if (i > 800) {
                    break;
                }
            }
            testingTask.printGoalStructureStatus();

            // goal status should be success
            assertTrue(testAgent.success());
            // close
            testAgent.printStatus();

            // done. Dump the collected data to csv files:
            exportToCSV(csvData_goalQuestIsCompleted, "data_goalQuestCompleted.csv");
            exportToCSV(csvData_goalGetMuchPoints, "data_goalGetMuchPoints.csv");
        } finally {
            environment.close();
        }
    }
}
